// right-sidebar/src/App.vue
<template>
  <div class="right-sidebar">
  <div>
    <h3>Right sidebar Application in</h3>
    <img src="./assets/logo.png" class="vue-logo">
   </div> 
  </div>
</template>

<script>

export default {
  name: 'App',
}
</script>

<style>
.right-sidebar{
  background-color: #b1ffdd;
  font-size: 18px;
  font-weight: bold;
  text-align: center;
  height:100%;
  display: flex;
  justify-content: center;
  align-items: center;
}
.vue-logo{
  height:100px;
}
</style>

// footer/src/App.svelte
<script>
</script>

<div class="footer">
	Footer Application in
	 <img src="http://localhost:3004/svelte.png" class="svelte-logo"/>
</div>
<style>
	.footer{
		background-color: #aaa;
		font-size: 18px;
		font-weight: bold;
		text-align: center;
		height:100%;
		display: flex;
		justify-content: center;
		align-items: center;
	}
	.svelte-logo{
		margin-left:'10px';
		height:50px;
	}

</style>
